### ISSUE TITLE
Front end - Status [General Issue]

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/ecommerce_example#243]
This issue is for tracking Front end tasks:
- [x] Get product from Product micro service with rating #226 
- [x] Register and Login #214 
- [ ] #245 
- [ ] Get logged user information: uuid, username.
- [ ] Authz - Get logged user roles.
- [ ] Product detail: add extra information #239 
- [x] Cart #238 
- [x] Integrate #256 
- [ ] Common config file #225 
- [ ] #283
